import { test } from '@playwright/test';
import {
  playChord,
  releaseAllKeys,
} from '../utils/keyboard-helpers';
import { resetAppState, initializeApp, dismissTutorial } from '../utils/test-setup';
import {
  expectAudioToMatchSnapshot,
} from '../utils/audio-snapshots';

/**
 * Audio Snapshot Tests - Prog Wizard Progressions
 *
 * Tests jazz progressions generated by Prog Wizard:
 * - ii-V-I (major)
 * - I-vi-ii-V (turnaround)
 * - Tritone substitutions
 * - Progressions with voicing styles
 *
 * Total: ~15 tests
 */

// Skip on mobile (audio tests require desktop for synth)
test.skip(({ isMobile }) => isMobile, 'Audio tests require desktop viewport');

test.describe('Audio Combos - Prog Wizard', () => {
  test.beforeEach(async ({ page }) => {
    await resetAppState(page);
    await initializeApp(page);
    await dismissTutorial(page);
  });

  // Common jazz progressions
  test.describe('Jazz Progressions', () => {
    test('should generate and snapshot ii-V-I progression in C major', async ({ page }) => {
      // Open Prog Wizard
      const progWizardBtn = page.locator('[data-testid="open-prog-wizard"]');
      await progWizardBtn.click();

      // Select ii-V-I
      const progressionSelect = page.locator('[data-testid="progression-type"]');
      await progressionSelect.selectOption('ii-V-I');

      // Set root to C
      const rootSelect = page.locator('[data-testid="progression-root"]');
      await rootSelect.selectOption('C');

      // Generate
      const generateBtn = page.locator('[data-testid="generate-progression"]');
      await generateBtn.click();

      await page.waitForTimeout(200);

      // Close wizard
      const closeBtn = page.locator('[data-testid="close-prog-wizard"]');
      await closeBtn.click();

      // The progression should now be loaded (Dmin7 - G7 - Cmaj7)
      const progression = [
        { root: 'D', quality: 'min7', name: 'Dmin7' },
        { root: 'G', quality: 'dom7', name: 'G7' },
        { root: 'C', quality: 'maj7', name: 'Cmaj7' },
      ];

      for (let i = 0; i < progression.length; i++) {
        const chord = progression[i];

        await playChord(page, chord.root, chord.quality);
        await page.waitForTimeout(200);

        await expectAudioToMatchSnapshot(
          page,
          `progwizard-ii-V-I-C-chord${i + 1}-${chord.name.toLowerCase()}`,
          chord
        );

        await releaseAllKeys(page);
        await page.waitForTimeout(100);
      }
    });

    test('should generate and snapshot I-vi-ii-V turnaround in F major', async ({ page }) => {
      const progWizardBtn = page.locator('[data-testid="open-prog-wizard"]');
      await progWizardBtn.click();

      const progressionSelect = page.locator('[data-testid="progression-type"]');
      await progressionSelect.selectOption('I-vi-ii-V');

      const rootSelect = page.locator('[data-testid="progression-root"]');
      await rootSelect.selectOption('F');

      const generateBtn = page.locator('[data-testid="generate-progression"]');
      await generateBtn.click();

      await page.waitForTimeout(200);

      const closeBtn = page.locator('[data-testid="close-prog-wizard"]');
      await closeBtn.click();

      // Progression: Fmaj7 - Dmin7 - Gmin7 - C7
      const progression = [
        { root: 'F', quality: 'maj7', name: 'Fmaj7' },
        { root: 'D', quality: 'min7', name: 'Dmin7' },
        { root: 'G', quality: 'min7', name: 'Gmin7' },
        { root: 'C', quality: 'dom7', name: 'C7' },
      ];

      for (let i = 0; i < progression.length; i++) {
        const chord = progression[i];

        await playChord(page, chord.root, chord.quality);
        await page.waitForTimeout(200);

        await expectAudioToMatchSnapshot(
          page,
          `progwizard-turnaround-F-chord${i + 1}-${chord.name.toLowerCase()}`,
          chord
        );

        await releaseAllKeys(page);
        await page.waitForTimeout(100);
      }
    });

    test('should generate tritone substitution progression', async ({ page }) => {
      const progWizardBtn = page.locator('[data-testid="open-prog-wizard"]');
      await progWizardBtn.click();

      const progressionSelect = page.locator('[data-testid="progression-type"]');
      await progressionSelect.selectOption('tritone-sub');

      const rootSelect = page.locator('[data-testid="progression-root"]');
      await rootSelect.selectOption('C');

      const generateBtn = page.locator('[data-testid="generate-progression"]');
      await generateBtn.click();

      await page.waitForTimeout(200);

      const closeBtn = page.locator('[data-testid="close-prog-wizard"]');
      await closeBtn.click();

      // Progression includes tritone substitution
      const progression = [
        { root: 'D', quality: 'min7', name: 'Dmin7' },
        { root: 'D#', quality: 'dom7', name: 'Db7' }, // Tritone sub for G7
        { root: 'C', quality: 'maj7', name: 'Cmaj7' },
      ];

      for (let i = 0; i < progression.length; i++) {
        const chord = progression[i];

        await playChord(page, chord.root, chord.quality);
        await page.waitForTimeout(200);

        await expectAudioToMatchSnapshot(
          page,
          `progwizard-tritone-sub-C-chord${i + 1}-${chord.name.toLowerCase()}`,
          chord
        );

        await releaseAllKeys(page);
        await page.waitForTimeout(100);
      }
    });
  });

  // Prog Wizard + Voicing Styles
  test.describe('Prog Wizard + Voicing Styles', () => {
    const voicingStyles = ['close', 'drop2', 'drop3', 'rootlessA', 'rootlessB', 'shell'];

    test('should generate ii-V-I in drop2 voicing', async ({ page }) => {
      const progWizardBtn = page.locator('[data-testid="open-prog-wizard"]');
      await progWizardBtn.click();

      const progressionSelect = page.locator('[data-testid="progression-type"]');
      await progressionSelect.selectOption('ii-V-I');

      const rootSelect = page.locator('[data-testid="progression-root"]');
      await rootSelect.selectOption('C');

      const generateBtn = page.locator('[data-testid="generate-progression"]');
      await generateBtn.click();

      await page.waitForTimeout(200);

      const closeBtn = page.locator('[data-testid="close-prog-wizard"]');
      await closeBtn.click();

      const progression = [
        { root: 'D', quality: 'min7', name: 'Dmin7' },
        { root: 'G', quality: 'dom7', name: 'G7' },
        { root: 'C', quality: 'maj7', name: 'Cmaj7' },
      ];

      for (let i = 0; i < progression.length; i++) {
        const chord = progression[i];

        await playChord(page, chord.root, chord.quality);

        // Cycle to drop2
        await page.keyboard.press('Shift');
        await page.waitForTimeout(50);

        await page.waitForTimeout(200);

        await expectAudioToMatchSnapshot(
          page,
          `progwizard-ii-V-I-C-drop2-chord${i + 1}-${chord.name.toLowerCase()}`,
          chord
        );

        await releaseAllKeys(page);
        await page.waitForTimeout(100);
      }
    });
  });
});
